# Day 22: Creating and Slicing Arrays in NumPy

## Agenda
- Different Ways to Create Arrays
- Slicing in Arrays
- Speed, Performance, and Memory

## Different Ways to Create Arrays
NumPy provides multiple functions to create arrays efficiently.

### Using np.array() 

In [2]:
import numpy as np

arr_list = np.array([1, 2, 3, 4, 5])
arr_tuple = np.array((10, 20, 30))

In [3]:
print("Array from list:", arr_list)
print("Array from tuple:", arr_tuple)

Array from list: [1 2 3 4 5]
Array from tuple: [10 20 30]


### Using np.zeros() and np.ones()

In [4]:
zeros_arr = np.zeros((2,3))
ones_arr = np.ones((2,3))

In [ ]:
print("Zeros Array:\n", zeros_arr)
print("Ones Array:\n", ones_arr)
## Using np.arange()

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


## Using np.arange()

In [6]:
arr_range = np.arange(0, 10, 2)

In [7]:
print("Array using arange:", arr_range)

Array using arange: [0 2 4 6 8]


### Using np.linspace()

In [8]:
arr_linspace = np.linspace(0, 1, 5)

In [9]:
print("Array using linspace:", arr_linspace)

Array using linspace: [0.   0.25 0.5  0.75 1.  ]


### Using np.random

In [10]:
rand_arr = np.random.rand(2,3)
randn_arr = np.random.randn(2,3)
randint_arr = np.random.randint(1, 10, (2,3))

In [12]:
print("Random Uniform:\n", rand_arr)

Random Uniform:
 [[0.36059797 0.76999782 0.81230402]
 [0.68140801 0.96867943 0.4423237 ]]


In [13]:
print("Random Normal:\n", randn_arr)

Random Normal:
 [[ 0.51074877  0.34766646 -0.34412835]
 [-0.67708034 -1.27136722  1.12095531]]


In [14]:
print("Random Integers:\n", randint_arr)

Random Integers:
 [[7 7 8]
 [9 6 6]]


### Slicing in Arrays

#### Slicing allows extracting parts of arrays using the `:` operator.

In [15]:
arr = np.arange(10)

In [16]:
print("Original Array:", arr)

Original Array: [0 1 2 3 4 5 6 7 8 9]


In [17]:
print("Slice [2:7]:", arr[2:7])

Slice [2:7]: [2 3 4 5 6]


### Slicing in 1D Arrays

In [18]:
arr = np.arange(10)

In [19]:
print("First 5 elements:", arr[:5])

First 5 elements: [0 1 2 3 4]


In [21]:
print("Last 3 elements:", arr[-3:])

Last 3 elements: [7 8 9]


### Slicing in 2D Arrays

In [22]:
arr2d = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Original 2D Array:\n", arr2d)

Original 2D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [23]:
print("First row:", arr2d[0])
print("First column:", arr2d[:,0])
print("Subarray:\n", arr2d[0:2, 1:3])

First row: [10 20 30]
First column: [10 40 70]
Subarray:
 [[20 30]
 [50 60]]


### Step Size in Slicing

In [24]:
arr = np.arange(20)

In [25]:
print("Array:", arr)

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [26]:
print("Slice with step [::2]:", arr[::2])

Slice with step [::2]: [ 0  2  4  6  8 10 12 14 16 18]
